# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='update',
            new_name='update_at',
        ),
    ]
